In [2]:
import pandas as pd 
import numpy as np

pd.__version__
np.__version__

'1.26.4'

## Cheat Sheet

[Pandas Documentation](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

In [7]:
series = pd.Series([10,20,20,40,50])
series

0    10
1    20
2    20
3    40
4    50
dtype: int64

In [11]:
series = pd.Series([10,20,20,40,50], index=['a','b','c','d','e'])
series

a    10
b    20
c    20
d    40
e    50
dtype: int64

In [5]:
series.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
series.values

array([10, 20, 20, 40, 50])

In [12]:
#Acccessing values

series['a']

10

In [13]:
#posistion indexing

series.iloc[0]

10

In [16]:
data = [['Adrian', 20], ['Bethany', 23], ['Chloe',41]]
df = pd.DataFrame(data, columns=['Name', "Age"])
df

      Name  Age
0   Adrian   20
1  Bethany   23
2    Chloe   41

# Use Documentation 

[Pandas_Documentation](https://pandas.pydata.org/docs/)

In [18]:
dict_list = [{'Name':'Tom'},{'Name':'Jane','Sales':300, 'Job Title':'Sales'},{'Name':'Jane','Sales':300, 'Job Title':'Sales'},{'Name':'Steve','Sales':350},{'Name':'Lucy','Sales':400,'Job Title':'Sales', 'Location':'London'}]
df = pd.DataFrame(dict_list)
df

    Name  Sales Job Title Location
0    Tom    NaN       NaN      NaN
1   Jane  300.0     Sales      NaN
2   Jane  300.0     Sales      NaN
3  Steve  350.0       NaN      NaN
4   Lucy  400.0     Sales   London

In [20]:
df.isnull().sum()

Name         0
Sales        1
Job Title    2
Location     4
dtype: int64

In [ ]:
#removes rows with too many null na values 
#this doesn't chnage teh data frame its just a view method 
df.dropna(thresh=3)

   Name  Sales Job Title Location
1  Jane  300.0     Sales      NaN
2  Jane  300.0     Sales      NaN
4  Lucy  400.0     Sales   London

In [26]:
df.fillna(0)

    Name  Sales Job Title Location
0    Tom    0.0         0        0
1   Jane  300.0     Sales        0
2   Jane  300.0     Sales        0
3  Steve  350.0         0        0
4   Lucy  400.0     Sales   London

In [ ]:
df['Sales'].fillna(0)

0      0.0
1    300.0
2    300.0
3    350.0
4    400.0
Name: Sales, dtype: float64

In [33]:
df['Filled_sales'] = df['Sales'].fillna(df['Sales'].mean())
df

    Name  Sales Job Title Location  Filled_sales
0    Tom    NaN       NaN      NaN         337.5
1   Jane  300.0     Sales      NaN         300.0
2   Jane  300.0     Sales      NaN         300.0
3  Steve  350.0       NaN      NaN         350.0
4   Lucy  400.0     Sales   London         400.0

In [32]:
df['Sales'].mean()

337.5

In [ ]:
#Interpolate
#Fills null values based on a linear line of best fit 
#doesn't mess up oveall trends

In [36]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [38]:
df.drop_duplicates(inplace=True)
df

    Name  Sales Job Title Location  Filled_sales
0    Tom    NaN       NaN      NaN         337.5
1   Jane  300.0     Sales      NaN         300.0
3  Steve  350.0       NaN      NaN         350.0
4   Lucy  400.0     Sales   London         400.0